name: osx

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        config:
          - preset: arm64-osx-clang-release

    runs-on: macos-latest

    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/.vcpkg_cache
      VCPKG_BINARY_SOURCES: "default"

    steps:
      - uses: actions/checkout@v4

      - name: vcpkg-cache-directory
        run: mkdir -p $VCPKG_DEFAULT_BINARY_CACHE

      - name: vcpkg-cache-restore
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: install-tools-macos
        run: |
          brew install llvm@22 ninja cmake doxygen
          echo "/opt/homebrew/opt/llvm@22/bin" >> $GITHUB_PATH

      - name: cmake-configure
        run: cmake --preset ${{ matrix.config.preset }}

      - name: cmake-build
        run: cmake --build --preset ${{ matrix.config.preset }} --parallel $(( $(nproc --all) + 1 ))

      - name: cmake-test
        run: ctest --preset ${{ matrix.config.preset }} --parallel $(( $(nproc --all) + 1 ))